### ISSUE TITLE
unable to add EXT Temp Sensor

### ISSUE THREAD

**Issue by ajdezigns** [ollo69/ha_tuya_custom#20]
Hey having a bit of a issue with using the Device parameters (configuration.yaml) function of this to try to add a temperature readout to my AC

`tuya_custom:
  devices_config:
    - device_name: Pinguino 
      unit_of_measurement: "C" 
      temp_divider: 1 
      curr_temp_divider: 1  
      ext_temp_sensor: sensor.temperature_6 `
OR
`tuya_custom:
  devices_config:
    - device_name: climate.pinguino_ac 
      unit_of_measurement: "C" 
      temp_divider: 1 
      curr_temp_divider: 1  
      ext_temp_sensor: sensor.temperature_6 `
either way the settings of this unit show as
`hvac_modes:
  - 'off'
  - heat_cool
min_temp: 7
max_temp: 35
target_temp_step: 1
current_temperature: null
tuya_device_id: 84680300d8bfc053423e
friendly_name: Pinguino
supported_features: 0
`
having a null in the current temp feild

**Comment by ollo69** [comment]
In Yaml indentation is important!!!
Try:

```
tuya_custom: 
   devices_config: 
      - device_name: Pinguino 
        unit_of_measurement: "C" 
        ext_temp_sensor: sensor.temperature_6
```

If not work check  HA log file
