### ISSUE TITLE
No devices showing after install

### ISSUE THREAD

**Issue by grantwils** [ollo69/ha_tuya_custom#24]
Forgive me as I'm clearly doing something wrong. 

I installed this to get my colourwheel on my RGB spotlights. 
Firstly i uninstalled the standard tuya integration.
Then I installed ha_tuya_custom
This is my config
tuya_custom:
```
  username: <my@email>
  password: !secret tuya_pw
  devices_config:
    - device_name: US Spotlight - Murdo # this is mandatory with at least one of the other keys
      support_color: true # true or false, force color support for device
```

US Spotlight - Murdo <is the friendly name of an RGB spotlight which previously worked (without RGB)

I cannot get any of the previous devices to show with or without the device name. Nothing shows up anywhere in HA. 
I have no errors in logs.
What did I do wrong please?
