### ISSUE TITLE
Thermostat not working in HA (temperature change not working)

### ISSUE THREAD

**Issue by artkrz** [ollo69/ha_tuya_custom#37]
Hi,

I'm using MOES Zigbee Radiator Actuator HY368 with Tuya app and it shows up in HA. I've added following to my config:

```
tuya_custom:
  devices_config:
    - device_name: Kitchen
      unit_of_measurement: "C"
      temp_divider: 10
```

Temperature shows up but when I adjust it it goes red, sometimes goes back briefly to what it was and then thermostat (entity) goes unavailable.

Please let me know how can I help to fix it.
